### PR TITLE
fix mutable default

### PR DESCRIPTION
**Pull request by ApexArray**
Fixes multiple email attachments as described in comments of [#822](https://github.com/TheSpaghettiDetective/obico-server/issues/822#issuecomment-1745879328)

### CODE REVIEW

**Comment by kennethjiang** [comment]
Good PR. Function parameter defaults in python can have surprising behavior.

**Comment by ApexArray** [comment]
@kennethjiang yes indeed, I've been guilty of it myself. Thanks for responding and merging the PR so quickly!

Also, I sent you Discord PM about another matter. Not sure if you got the notification so I figured I'd ping you here.

**Comment by kennethjiang** [comment]
What's your discord ID? I have responded to all discord PMs as of now. So if you haven't got my response, I must have missed you. Please send it again.

**Comment by ApexArray** [comment]
Weird. I’ve definitely seen that happen before though.

I am Apex3d on discord. I’ll try sending a friend invite.

**Pull request merged**
