### PR TITLE
Webhook Notification

### PR DESCRIPTION
**Pull request by lnjustin**
It feels odd to open a PR when it's unlikely that it's ready for acceptance yet. I haven't tested it yet, but could use some input. 

As you can see, I've updated the following files with a new 'webhook' notification plugin:
frontend/src/notifications/plugins.js
frontend/src/notifications/plugins/webhook.vue
backend/notifications/plugins/webhook/init.py

I ran
docker compose up --build -d
as if upgrading the server (https://www.obico.io/docs/server-guides/ops/)

But the webhook plugin still doesn't show up on the frontend page, so I must be missing something....Haven't been able to test my changes yet...

Did I miss any files that need creation/updating for a new notification plugin? Or am I running the right docker command?

### CODE REVIEW

**Comment by encetamasb** [comment]
Did you rebuild the frontend before restarting the services? `cd frontend && yarn && yarn build ` This does not happen automatically.

**Comment by lnjustin** [comment]
Ah, that must be it. I didn't rebuild the frontend. I'm guessing I need to install yarn though....I tried executing those yarn commands from within the frontend folder (which indeed has package.json with the build script listed). But get the no command found response. So will have to look into how/where to install yarn in this docker container environment....

**Comment by encetamasb** [comment]
This might help, although this dev setup is no longer maintained.

https://github.com/TheSpaghettiDetective/obico-server/blob/release/backend/Dockerfile.dev#L9

https://github.com/TheSpaghettiDetective/obico-server/blob/release/docker-compose.yml#L7

**Comment by lnjustin** [comment]
Ok well I'm a bit out of my element on this development environment. I'm pretty sure the files I created and updated as part of this PR are a solid head start on implementing this feature (maybe even all that's needed). Perhaps this would be short work to test for someone who already has the development environment up and running.

**Comment by encetamasb** [comment]
I don't think there is any docs or an official way to develop obico webapp.

I would do the following. This gives you a limited devenv with hot-reload:

(1) Create a `docker-compose.override.yml` file with the following content:

```
version: '2.4'

services:
  web:
    build:
      context: backend
      dockerfile: 'Dockerfile.dev'
    command: sh -c 'sleep infinity'
```

(2) Rebuild web 

`docker-compose build web`

(3) Start devenv

`docker-compose up`

(4) Start webserver

`docker-compose exec web /bin/bash
cd /app
WEBPACK_LOADER_ENABLED=True DEBUG=True ./manage.py runserver -v 3 0.0.0.0:3334
`

(5) Start webpack dev server

`docker-compose run -p 7070:7070 --rm web yarn --cwd /frontend serve`

(6) Visit `http://localhost:3334` and edit files

(7) When all good, build assets and check the whole thing without webpack dev-server

`docker-compose run -p 7070:7070 --rm web yarn --cwd /frontend build`

and start the python worker in the web container with

`WEBPACK_LOADER_ENABLED=False DEBUG=False ./manage.py runserver -v 3 0.0.0.0:3334`

(8) PR changes without (!) any rebuilt assets (static/*)

I hope this helps.

**Comment by lnjustin** [comment]
Thanks for that step-by-step. I get the following when executing docker-compose exec web /bin/bash though:
service "web" is not running container #1

At this point, I would need to be spoon fed how to get the development environment up and running, something that I don't expect anyone to do. I think time would be better spent if someone else is willing and able to test the updates that I've proposed. They are rather simple as this is not a complicated feature to implement (tho apparently getting a development environment going is more complicated than it should be...)

**Comment by lnjustin** [comment]
Well, I got past that command. Now when running the next one tho I get an error that there is no file manage.py despite there clearly being one when I run ls from the app folder
WEBPACK_LOADER_ENABLED=True DEBUG=True ./manage.py runserver -v 3 0.0.0.0:3334

Ugh.

**Comment by encetamasb** [comment]
> Well, I got past that command. Now when running the next one tho I get an error that there is no file manage.py despite there clearly being one when I run ls from the app folder WEBPACK_LOADER_ENABLED=True DEBUG=True ./manage.py runserver -v 3 0.0.0.0:3334
> 
> Ugh.

Please enter with 

`docker-compose exec web /bin/bash`

and then inside run

`cd /app && python manage.py`

You should see the list of available django commands. If you get an error, please give me the exact output. Do you use linux/osx for host?

**Comment by lnjustin** [comment]
Ok, that worked. Getting there....

docker-compose run -p 7070:7070 --rm web yarn --cwd /frontend serve
gives me this:
[+] Running 1/0
 - Container obico-server-ml_api-1  Running                                                                        0.0s
yarn run v1.22.19
$ vue-cli-service serve
/bin/sh: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

That website doesn't seem to help me...any ideas on this one?

**Comment by encetamasb** [comment]
> Ok, that worked. Getting there....
> 
> docker-compose run -p 7070:7070 --rm web yarn --cwd /frontend serve gives me this: [+] Running 1/0 Container obico-server-ml_api-1 Running 0.0s yarn run v1.22.19 $ vue-cli-service serve /bin/sh: vue-cli-service: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> That website doesn't seem to help me...any ideas on this one? Thanks so much for your help btw!

Install dependencies first then, at least the first time:

`docker-compose run -p 7070:7070 --rm web /bin/sh -c "yarn --cwd /frontend && yarn --cwd /frontend serve"`

**Comment by lnjustin** [comment]
Alright, that worked. Unfortunately, though, I get an error when i try to access.

 DONE  Compiled successfully in 49887ms                                                                       1:47:29 PM


  App running at:
  - Local:   http://localhost:7070/

  It seems you are running Vue CLI inside a container.
  Access the dev server via http://localhost:<your container's external mapped port>http://localhost:7070/


Accesssing http://localhost:7070/
gives
Error
Cannot GET /

**Comment by encetamasb** [comment]
> Alright, that worked. Unfortunately, though, I get an error when i try to access.
> 
> DONE Compiled successfully in 49887ms 1:47:29 PM
> 
> App running at:
> 
> * Local:   http://localhost:7070/
> 
> It seems you are running Vue CLI inside a container. Access the dev server via http://localhost:<your container's external mapped port>http://localhost:7070/
> 
> Accesssing http://localhost:7070/ gives Error Cannot GET /

That's a good problem.

Make sure your python worker is up in dev mode, and visit localhost:3334 . You can check the page source, it should load assets from the :7070 address, successfully. 

I suppose you devenv is ready!

**Comment by lnjustin** [comment]
Visiting localhost:3334 produces
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

I'm pretty sure my python worker is up in dev mode, but honestly don't know how to confirm that. Then there's this warning that showed up when I executed docker-compose run -p 7070:7070 --rm web /bin/sh -c "yarn --cwd /frontend && yarn --cwd /frontend serve"
 warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".

**Comment by encetamasb** [comment]
> Visiting localhost:3334 produces localhost didn’t send any data. ERR_EMPTY_RESPONSE
> 
> I'm pretty sure my python worker is up in dev mode, but honestly don't know how to confirm that. Then there's this warning that showed up when I executed docker-compose run -p 7070:7070 --rm web /bin/sh -c "yarn --cwd /frontend && yarn --cwd /frontend serve" warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".

Order of launch is unfortunately important. Start with `docker-compose up` first. web container must be running before you start the webpack-dev-server. In this minimal setup that's using `web` too, but it should not start it. 

Stop all and try again in the right order.

**Comment by encetamasb** [comment]
Let's simplify the setup. Let's exec into web in case of webpack-dev-server too, then starting order is not important anymore. You need to assign port 7070 to web in override file.

---

#### 1. Create a `docker-compose.override.yml` file with the following content:

```
version: '2.4'

services:
  web:
    build:
      context: backend
      dockerfile: 'Dockerfile.dev'
    command: ['sleep', 'infinity']
    ports:
      - 127.0.0.1:7070:7070
```

This overrides the image file, `Dockerfile.dev` has yarn installed.
Disabled python worker too (with sleep as command), as you will start that manually.
Added :7070 port for webpack-dev-server.

#### 2. Rebuild web 

`docker-compose build web`


#### 3. Start dev env

`docker-compose up`


#### 4. Start python worker in `web` (backend)

Enter into container using

`docker-compose exec web /bin/bash`

and then start python worker in _dev mode_, inside the container (in `/app` dir, that's the default path)

`
WEBPACK_LOADER_ENABLED=True DEBUG=True ./manage.py runserver -v 3 0.0.0.0:3334
`

Don't forget to install extra requirements or migrate database in advance or when you need to do that, those can be done inside this container as well.

`pip install -r requirements.txt && ./manage.py migrate`


#### 5. Start webpack dev server (frontend) in web container

In another tab of your terminal launch

`docker-compose exec web /bin/bash`

and then start webpack-dev-server:

`cd /frontend && yarn && yarn serve`

#### 6. Implement your feature

Visit `http://localhost:3334` and edit source files (on your host machine). Some changes get hot-reloaded, others don't. Check the outputs of  backend/frontend processes, and fix issues.

#### 7. Final check

When all good, build assets and check the whole thing without webpack dev-server.

Build assets with

`docker-compose run --rm web yarn --cwd /frontend build`

Run `collectstatic` inside web container:

`./manage.py collectstatic -v 2 --noinput`

And start the python worker in the web container with

`WEBPACK_LOADER_ENABLED=False DEBUG=False ./manage.py runserver -v 3 0.0.0.0:3334`

Check that your feature still works as expected.


#### 8. Create PR without (!) any (p)rebuilt assets (static/*)

I hope this helps.

**Comment by lnjustin** [comment]
Got it!!! Thanks so much. For my own reference, this turned out to be the commands:

1. Create a docker-compose.override.yml file with the following content:
version: '2.4'

services:
  web:
    build:
      context: backend
      dockerfile: 'Dockerfile.dev'
    command: ['sleep', 'infinity']
This overrides the image file, Dockerfile.dev has yarn installed.
Disabled python worker too (with sleep as command), as you will start that manually.

2. Rebuild web
docker-compose build web

3. Start dev env
docker-compose up

4. Start python worker in web (backend)
Enter into container using

docker-compose exec web /bin/bash
cd /app && python manage.py

and then start python worker in dev mode, inside the container (in /app dir, that's the default path)

cd /app && WEBPACK_LOADER_ENABLED=True && python manage.py runserver -v 3 0.0.0.0:3334

5. Start webpack dev server (frontend)
In another tab of your terminal launch

docker-compose run -p 7070:7070 --rm web yarn --cwd /frontend serve

**Comment by lnjustin** [comment]
Ok I think I need to do what you said before:
 check /api/v1/notification_settings/available_plugins

I can't find /api/vi folder in the container though. Where is this?

**Comment by lnjustin** [comment]
Got it. Dev env up and running thanks to you. And my webhook plugin loaded. Now to just figure out how to get some logging going. The debug log on the development server is quite busy. Either I'm missing my log output or I'm looking in the wrong place. 
Trying to find the output of python code
LOGGER = logging.getLogger(__name__)
LOGGER.debug("test log output")

**Comment by encetamasb** [comment]
Yes, db log level is a bit verbose, set `"ERROR" ` here https://github.com/TheSpaghettiDetective/obico-server/blob/release/backend/config/settings.py#L216

As a shortcut, you will see output of this in normal circumstances:

```
LOGGER = logging.getLogger()
LOGGER.error("test log output")
```

As you have `send_test_message` method implemented, perhaps focus on that first. Grab your configured plugin `:id` here

`http://localhost:3334/api/v1/notification_settings/` 

and launch test message sending with that `:id` from browser console (requires an active session, so first sign in), something like 

`fetch('http://localhost:3334/api/v1/notification_settings/:id/send_test_message/', {method: 'POST'})`

**Comment by lnjustin** [comment]
Hmm. I get a 403 forbidden despite being logged in. Any idea?

**Comment by lnjustin** [comment]
Figured out that I needed to add -u and/or PYTHONUNBUFFERED=0 to see the log unbuffered

**Comment by lnjustin** [comment]
Or not. Guess that didn't actually work

**Comment by encetamasb** [comment]
> Hmm. I get a 403 forbidden despite being logged in. Any idea?

Without the exact error message I cannot help. Check logs of python worker.

> Also, do changes to _init_.py in \backend\notifications\plugins\webhook get hot-reloaded? Or do I have to rebuild?

No need to rebuild. You need to restart the python worker every time you change the code of a plugin file because .. it's complicated. 

It can be helped though. Add plugin files to the watcher directly:

1. Create AppConfig for notifications

Create `backend/notifications/apps.py` with the following content:

```
from pathlib import Path

from django.apps import AppConfig
from django.utils.autoreload import autoreload_started
from django.conf import settings


class NotificationsAppConfig(AppConfig):
    name = 'notifications'

    def ready(self):
        if settings.DEBUG:
            autoreload_started.connect(add_plugins_to_watchdog)


def add_plugins_to_watchdog(sender, **kwargs):
    for p in Path(settings.BASE_DIR + '/notifications/plugins').iterdir():
        if p.is_dir() and Path(p / '__init__.py').exists():
            sender.watch_dir(p.absolute(), '*.py')
```

2. Update settings

Under `INSTALLED_APPS` in `backend/config/settings.py` change

`"notifications"`  entry to `"notifications.apps.NotificationsAppConfig"`

**Comment by encetamasb** [comment]
> Or not. Guess that didn't actually work

Logging?

The problem is that your logger is not configured properly.

Add your logger here, 

https://github.com/TheSpaghettiDetective/obico-server/blob/release/backend/config/settings.py#L219

with the same structure as root.  You might want `"DEBUG"` level instead of `"INFO"` for your logger.

**Comment by lnjustin** [comment]
Great, logging is working now! So I can actually develop ha. Slowly getting there...

The final thing I have to figure out is why the POST isn't working. Logs shows this is being called on printer events, but I'm not receiving anything at the other end....

  ```
  def execute_webhook(
        self,
        url: str,
        eventData: Dict,
        timeout: float = 5.0,
    ) -> None:


        test_url = "https://webhook.site/15d87b31-71d2-47c4-956f-afd272589bca"
        LOGGER.error("Executing webhook to %s with eventData: %s", test_url, eventData)
        headers = {'content-type': 'application/json'}

        #Neither of these request calls work (I've imported json FYI)
        response = requests.post(test_url, json=eventData, headers=headers, timeout=timeout)
        #response = requests.post(test_url, data=json.dumps(eventData), headers=headers, timeout=timeout)
        response.raise_for_status()
```

**Comment by lnjustin** [comment]
Ok, got it. Think it was an issue with the way I was defining the eventData. I've got it working now. Thanks so much for all of your help!!

**Comment by lnjustin** [comment]
I'm having trouble finalizing the build. This command isn't working:

Run collectstatic inside web container:

./manage.py collectstatic -v 2 --noinput

By web container, do you mean backend/static_build?

I tried running the below from within /backend, but get a no such file or directory for /static_build

cd /static_build && python manage.py collectstatic -v 2 --noinput

Any idea?

**Comment by encetamasb** [comment]
> I'm having trouble finalizing the build. This command isn't working:
> 
> Run collectstatic inside web container:
> 
> ./manage.py collectstatic -v 2 --noinput
> 
> By web container, do you mean backend/static_build?
> 
> I tried running the below from within /backend, but get a no such file or directory for /static_build
> 
> cd /static_build && python manage.py collectstatic -v 2 --noinput
> 
> Any idea?

`cd /app && python manage.py ...`

You can find the original command in `docker-compose.yaml`

Yes, it probably stores the output in static_build, but in theory you don't have anything to do with that. 

Next, when you set `DEBUG=False` for `runserver` it must provide the prebuilt assets (you can check source of rendered html pages), instead of urls pointing to weback dev server.

**Comment by lnjustin** [comment]
Closing this PR in favor of a renewed one ready for review. Thanks @encetamasb!

**Pull request closed without merging**
